### ISSUE TITLE
As a developer, I want to use express.js to implement the server, so that all developers are familiar with the language used

### ISSUE THREAD

**Issue by sam-gaylert** [nyu-software-engineering/trading-dashboard#5]
Acceptance criteria:
- [x] Get a basic application running in one of these two libraries 

Estimated work:
Small

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-trading-dashboard - things that are spikes are not also user stories... please label correctly.  Spikes are internal tasks not directly related to user experience.  User stories directly relate to what users can do with the app.

Also, please learn Markdown and use sub-headings for Acceptance Criteria and Estimate of Work in all your user stories.

Otherwise, nice job assigning issues to individual members.
